name: package
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'

env:
  FILENAME: sendEmail
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.181'
          java-package: jdk
          architecture: x64
      - name: Set up Maven
        uses: stCarolas/setup-maven@v3
        with:
          maven-version: 3.6.1
      - name: Change Maven Settings
        uses: whelk-io/maven-settings-xml-action@v12
        with:
          servers: '[{ "id": "github", "username": "${{ secrets.PRIVATE_GITHUB_REPO_USER }}", "password":"${{ secrets.PRIVATE_GITHUB_REPO_PASSWORD }}"}]'
      - name: Build
        run: mvn clean package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILENAME }}.zip
          # A file, directory or wildcard pattern that describes what to upload
          path: ./target/${{ env.FILENAME }}.zip